name: Deploy  

on: 
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host droplet
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy site
        run: |
          ssh droplet bash -s << 'SCRIPT'
            set -e
            if [ ! -d /root/portfolio ]; then
              git clone https://github.com/dddictionary/portfolio.git /root/portfolio
            fi
            cd /root/portfolio
            git fetch
            git reset origin/main --hard
            cat > .env <<EOF
          MYSQL_DATABASE=$MYSQL_DATABASE
          MYSQL_USER=$MYSQL_USER
          MYSQL_PASSWORD=$MYSQL_PASSWORD
          MYSQL_HOST=$MYSQL_HOST
          URL=$URL
          CERTBOT_EMAIL=$CERTBOT_EMAIL
          EOF
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
          SCRIPT
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          URL: ${{ secrets.URL }}
          CERTBOT_EMAIL: ${{ secrets.CERTBOT_EMAIL }}